apiVersion: v1
kind: Service
metadata:
  name: {{ include "bux-server.name" . }}
  labels:
    {{- include "bux-server.labels" . | nindent 4 }}
  {{ if has "alb" $.Values.ingressControllers }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ include "bux-server.name" . }}.{{ .Values.global.domainName }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "bux-server.selectorLabels" . | nindent 4 }}
