apiVersion: v2
name: spv-wallet-web-frontend
description: A Helm chart for a frontend of custodial web wallet based on spv-wallet
type: application
version: 0.8.4
appVersion: "v0.41.0"
dependencies: []
