apiVersion: v2
name: spv-wallet-web-backend
description: A Helm chart for a backend for frontend of custodial web wallet based on spv-wallet
type: application
version: 0.11.0
appVersion: "v0.40.0-RC1"
dependencies:
  - name: postgresql
    condition: postgresql.enabled
    version: 13.2.0
    repository: https://charts.bitnami.com/bitnami
