apiVersion: v2
name: pulse
description: A Helm chart for Kubernetes

type: application

version: 0.3.0

appVersion: "v0.8.1"

dependencies:
  - name: postgresql
    condition: postgresql.enabled
    alias: postgresql-pulse
    version: 13.2.0
    repository: https://charts.bitnami.com/bitnami