apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bux-wallet-backend.name" . }}-env
  labels:
    {{- include "bux-wallet-backend.labels" . | nindent 4 }}
data:
  DB_HOST: '{{- .Release.Name}}-postgresql'
  BUX_SERVER_URL: 'http://{{- .Release.Name}}-server/v1'
  HTTP_SERVER_CORS_ALLOWEDDOMAINS: 'https://{{- .Release.Name}}-wallet.{{ .Values.global.domainName }}'
  BUX_PAYMAIL_DOMAIN: '{{ .Values.global.domainName }}'