apiVersion: v2
name: bux-server
description: A Helm chart for Kubernetes

type: application

version: 0.2.0

appVersion: "v0.12.0"

dependencies:
  - name: postgresql
    condition: postgresql.enabled
    alias: postgresql-server
    version: 13.2.0
    repository: https://charts.bitnami.com/bitnami
  - name: redis
    condition: redis.enabled
    version: 18.2.0
    repository: https://charts.bitnami.com/bitnami
