apiVersion: v2
name: bux-wallet-backend
description: A Helm chart for Kubernetes

type: application

version: 0.2.0

appVersion: "v0.23.0"

dependencies:
  - name: postgresql
    condition: postgresql.enabled
    alias: postgresql-wallet
    version: 13.2.0
    repository: https://charts.bitnami.com/bitnami
